# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Quantile <- function(x, probs) {
    .Call('_cqrfactor_Quantile', PACKAGE = 'cqrfactor', x, probs)
}

#' @title Function to compute the composite quantile factors and loadings.
#' 
#' @description This function uses the MM algorithm to compute the composite 
#'  quantile factors and factor loadings for a given number of factors.
#' 
#' @param y A t by n matrix with n variables and t observations each.
#' @param tau A vector of quantile positions, and \code{tau = (1:q)/(q+1)}, 
#'  where q is the numbrer of quantiles.
#' @param q The number of quantiles.
#' @param r The number of factors.
#' @param tol Tolerance for convergence of the MM algorithm. Defaults to 1e-6
#'  when the minconver option is 1. When the minconver option is 0, the 
#'  algorithm's convergence depends on the average parameter value change between
#'  iteration steps, and it can take long time to converge. We recommend to use 
#'  a bigger number such as 1e-3 when minconver = 1.
#' @param maxit The maximum iteration number between factor estimation and factor 
#'  loading estimation. Defaults to 500.
#' @param maxit_factor The maximum iteration number in the MM algorithm in factor
#'  estimation. Defaults to 500.
#' @param maxit_loading The maximum iteration number in the MM algorithm in factor
#'  loading estimation. Defaults to 500.
#' @param minconver If the value is 1, the algorithm converges when the minimum
#'  change among all estimated parameters between two iteration steps is less
#'  than or equal to tol. If the value is 0, the algorithm converges when the 
#'  average change of all estimated parameters is less than or equal to tol.
#'  This can take a long computation time. If minconver = 0, set tol to a bigger
#'  number such as 1e-3. Defaults to 1. 
#' @param seed A non-negative integer for random seed used in the C++ function \code{srand} to
#'  initialize factor values. If seed is -1, the initial value of the
#'  factors will be set to the eigenvectors of the outer product of the data
#'  matrix y. Defaults to 1.
#' 
#' @return \code{mmfactor} returns a list with the following components:
#'  \item{fmat}{The estimated factors, a t by r matrix, where r is the number
#'  of factors.} \item{lmat}{The estimated factor loading matrix, an n by r 
#'  matrix.} \item{quantiles}{The q estimated quantiles of the error term.} 
#'  \item{iteration_mat}{A \code{maxit} by 3 matrix. Each row corresponds to an
#'  iteration between factor estimation and factor loading estimation. The 
#'  second element is the number of iterations the MM uses for estimating the 
#'  factors while the third element is the number of iteration for the factor
#'  loadings.}
#' 
#' @examples
#' \dontrun{
#' 
#' }
#' 
mmfactor <- function(y, tau, q = 5L, r = 3L, tol = 1e-6, maxit = 500L, maxit_factor = 500L, maxit_loading = 500L, minconver = 1L, seed = 1L) {
    .Call('_cqrfactor_mmfactor', PACKAGE = 'cqrfactor', y, tau, q, r, tol, maxit, maxit_factor, maxit_loading, minconver, seed)
}

